#!/bin/sh
file=$1.dvi
eval "$(hexdump -s15 -n `hexdump -s14 -n1 -e '"%u"' $file` -v -e '"%c"' $file | sed 's/.* /p=/;s/x/sp,/;s/[+-][0-9]*/sp x=& y=/')"
export TEXCONFIG=~/th:~/dvips
export DVIPSHEADERS=~/th/pfb:~/dvips
export TEXFONTS=~/tex/TeXfonts
t=a4
[ $p = 55380990sp,39158276sp ] && t='a4 -t landscape'
export err=/tmp/err.$$
( ~/dvips/dvips -t $t -O $((x-4736287))sp,$((y-4736287))sp -P t1 -q -o /dev/stdout $file || touch $err ) | ps2pdf - $1.pdf
ret=$?
if [ -e $err ]; then
  echo DVIPS ERROR
  rm -f $1.pdf $err
  exit
elif [ $ret != 0 ]; then
  echo PS2PDF ERROR
  rm -f $1.pdf $err
  exit
fi
rm -f $err
